import fs from 'node:fs/promises';
import {chromium} from 'playwright-core';
import {browserProxy,resolvePublic,webUrl} from './public-web.ts';
import type {BrowserEvidence} from './types.ts';
export async function inspectAsset(raw:string):Promise<BrowserEvidence>{
 const url=webUrl(raw);await resolvePublic(url.hostname);
 let executable=process.env.HALLAR_CHROME_PATH;
 if(!executable){for(const path of ['C:/Program Files/Google/Chrome/Application/chrome.exe','/usr/bin/chromium','/usr/bin/chromium-browser','/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/opt/google/chrome/chrome']){if(await fs.stat(path).then(()=>true).catch(()=>false)){executable=path;break;}}}
 if(!executable)throw new Error('Chromium unavailable in scout runtime');
 const proxy=await browserProxy();let browser;
 try{const env=Object.fromEntries(Object.entries(process.env).filter(([key,value])=>value!==undefined&&!/API_KEY|SECRET|TOKEN|PASSWORD|CREDENTIAL|AUTH/i.test(key))) as Record<string,string>;browser=await chromium.launch({executablePath:executable,headless:true,chromiumSandbox:true,env,proxy:{server:proxy.url,bypass:'<-loopback>'},args:['--proxy-bypass-list=<-loopback>','--force-webrtc-ip-handling-policy=disable_non_proxied_udp'],timeout:25000});const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1,acceptDownloads:false});await context.addInitScript(()=>{const w=window as unknown as {__h:{lcp:{startTime:number}[];long:number[]}};w.__h={lcp:[],long:[]};try{new PerformanceObserver(l=>{for(const e of l.getEntries())w.__h.lcp.push({startTime:e.startTime});}).observe({type:'largest-contentful-paint',buffered:true});new PerformanceObserver(l=>{for(const e of l.getEntries())w.__h.long.push(e.duration);}).observe({type:'longtask',buffered:true});}catch{}});const page=await context.newPage();const cdp=await context.newCDPSession(page);await cdp.send('Network.enable');await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});await page.coverage.startCSSCoverage();const response=await page.goto(url.href,{waitUntil:'domcontentloaded',timeout:45000});if(response?.status()!==200)throw new Error(`Asset returned HTTP ${response?.status()}`);await page.waitForLoadState('load',{timeout:20000}).catch(()=>{});await page.waitForTimeout(5000);
 const data=await page.evaluate(()=>{const n=performance.getEntriesByType('navigation')[0] as PerformanceNavigationTiming;const w=window as unknown as {__h:{lcp:{startTime:number}[];long:number[]}};return {url:location.href,navigation:n.toJSON(),fcp:performance.getEntriesByName('first-contentful-paint')[0]?.startTime??null,lcp:w.__h.lcp.at(-1)?.startTime??null,long:w.__h.long.length,resources:performance.getEntriesByType('resource').map(e=>{const r=e as PerformanceResourceTiming & {renderBlockingStatus?:string};return {url:r.name,encoded:r.encodedBodySize,decoded:r.decodedBodySize,end:r.responseEnd,blocking:r.renderBlockingStatus==='blocking'};})};});
 const finalUrl=webUrl(data.url);await resolvePublic(finalUrl.hostname);if(finalUrl.hostname.replace(/^www\./,'')!==url.hostname.replace(/^www\./,''))throw new Error('Asset left the explicitly associated site');
 const coverage=await page.coverage.stopCSSCoverage();const css=coverage.filter(c=>c.url&&c.text&&/^https?:/.test(c.url)).map(c=>{const r=data.resources.find(r=>r.url===c.url);const total=Buffer.byteLength(c.text??'');const used=c.ranges.reduce((n,x)=>n+Buffer.byteLength((c.text??'').slice(x.start,x.end)),0);return {url:c.url,encodedBytes:r?.encoded??0,decodedBytes:total,usedRangeBytes:used,outsideUsedRangesBytes:Math.max(0,total-used),blocking:r?.blocking??false};}).filter(c=>c.blocking&&c.decodedBytes>=20000).sort((a,b)=>b.outsideUsedRangesBytes-a.outsideUsedRangesBytes).slice(0,4);
 const nav=data.navigation as unknown as PerformanceNavigationTiming;return {url:data.url,status:200,observedAt:new Date().toISOString(),browser:browser.version(),viewport:'390 × 844; headless desktop Chromium with mobile layout; unthrottled CPU/network; fresh context; browser HTTP cache disabled',documentWaitMs:nav.responseStart-nav.requestStart,fcpMs:data.fcp,lcpMs:data.lcp,loadMs:nav.loadEventEnd,blockingEntries:data.resources.filter(r=>r.blocking).length,longTasks:data.long,headers:Object.fromEntries(Object.entries(response?.headers()??{}).filter(([k])=>['cache-control','content-encoding','content-type'].includes(k))),css,images:data.resources.filter(r=>/\.(png|jpe?g|webp)(\?|$)/i.test(r.url)&&r.encoded>1000000).sort((a,b)=>b.encoded-a.encoded).slice(0,3).map(r=>({url:r.url,bytes:r.encoded,endMs:r.end})),limits:['One instrumented first-load observation on a mobile-sized viewport, not a physical phone or production benchmark.','Bytes outside used CSS rule ranges may be needed by other interactions, pages or breakpoints. No safe-removal percentage or improvement measured.','Document waiting time includes network/server effects; no sole root cause or script attribution established.','No plugin was applied. Do not stack overlapping optimizers or change staging cache policy without authorization.']};
 }finally{if(browser)await browser.close().catch(()=>{});await proxy.close();}
}
