'use client';
import {useEffect} from 'react';
import {ProductEntry,ProductBrief} from './ui/product';
import {ResearchDesk} from './ui/research';
import {Outcomes} from './ui/outcomes';
import {ScoutAvatar} from './ui/scout-avatar';
import {useWorkspace} from './ui/use-workspace';
import {Arrow,Glyph,clean} from './ui/shared';
export default function Home(){
 const {s,patch,reset,analyze,scout}=useWorkspace();
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});},[s.screen]);
 const chapter=['landing','learning','profile'].includes(s.screen)?1:s.screen==='research'?2:3;
 return <div className={'app-shell immersive-shell screen-'+s.screen}><header className="app-header"><button className="brand" onClick={reset} aria-label="Hallar home"><span className="brand-mark"><svg viewBox="0 0 28 28"><path d="M8 22V6h4v6q9-6 9 3v7h-4v-7q-1-4-5 1v6z" fill="currentColor"/><path d="m20 4 4 0 0 4" fill="none" stroke="currentColor" strokeWidth="1.5"/></svg></span>hallar<span className="brand-dot">.</span></button><span className="header-thesis">Proof before pitch.</span>{s.screen!=='landing'&&<button className="text-button new-search" onClick={reset}>New search <Arrow/></button>}</header><main className="workspace">{s.screen!=='landing'&&<div className="journey-indicator" aria-label="Journey position"><span className={chapter===1?'current':''}><i/>Product brief</span><span className={chapter===2?'current':''}><i/>Find people</span><span className={chapter===3?'current':''}><i/>Useful proof</span></div>}{s.error&&<div className="error-banner" role="alert"><p>{clean(s.error)}</p><button className="icon-button" aria-label="Dismiss message" onClick={()=>patch({error:''})}><Glyph kind="cross"/></button></div>}{s.screen==='landing'&&<ProductEntry url={s.url} onUrl={url=>patch({url})} onAnalyze={()=>void analyze()} busy={s.busy||!s.ready}/>} {s.screen==='profile'&&s.profile&&<ProductBrief profile={s.profile} onChange={profile=>patch({profile})} onBack={reset} onScout={()=>void scout()} busy={s.busy} frozen={s.frozen} />} {['learning','research'].includes(s.screen)&&<ResearchDesk stage={s.stage} message={s.job?.message}/>} {s.screen==='results'&&s.job&&<div className="result-arrival"><Outcomes job={s.job} initial={s.job.result?.opportunities.some(o=>o.outcome==='QUALIFIED')?'QUALIFIED':s.job.result?.opportunities.some(o=>o.outcome==='INSUFFICIENT_EVIDENCE')?'INSUFFICIENT_EVIDENCE':'REJECTED'} frozen={s.frozen} onBrief={()=>patch({screen:'profile',job:null})} onScout={()=>void scout()}/></div>} {s.screen==='error'&&<section className="empty-scene"><ScoutAvatar stage="FAILED" compact/><span className="eyebrow">YOUR BRIEF IS STILL HERE</span><h1>This scout<br/><em>could not finish.</em></h1><p>{clean(s.job?.error??'The research could not complete. Your product brief is still here, ready for another attempt.')}</p><button className="button primary" onClick={()=>void scout()}>Retry scouting <Arrow/></button><button className="text-button" onClick={()=>patch({screen:'profile',job:null})}>Review product brief</button></section>}</main><footer className="app-footer"><span>Useful proof earns a better introduction.</span><span>You decide whether to engage.</span></footer></div>;
}
