'use client';
import {useEffect,useRef,useState} from 'react';
import type {Stage} from '../../core/types';
import {ScoutAvatar} from './scout-avatar';
import {Arrow,Glyph} from './shared';
import {Reveal} from './motion';
const chapters:{title:string;description:string;stage:Stage;note:string;marks:string[]}[]=[
 {title:'Tell Hallar what you actually do.',description:'Your product is the starting point. Hallar reads it, then gives you a brief you can correct, including what you cannot help with.',stage:'ANALYZING_PRODUCT',note:'Understanding, before assumptions.',marks:['What you solve','Who you help','Where you stop']},
 {title:'Hallar goes looking.',description:'People describe their pain in public every day. Hallar searches real conversations for people your product can genuinely help.',stage:'SCOUTING',note:'Find a person with relevant pain.',marks:['Real conversations','People with relevant pain','Original sources']},
 {title:'Most people get rejected.',description:'A familiar keyword is easy to find. A credible reason to help is harder. Weak fit, irrelevant needs and missing evidence do not become qualified opportunities.',stage:'QUALIFYING',note:'A clear no protects people and your time.',marks:['Weak fit / rejected','Missing proof / held','Relevant need / examined']},
 {title:'Proof before pitch.',description:'For a promising prospect with an associated public asset, Hallar verifies the fit and prepares useful proof. It separates what was observed from what might be true.',stage:'PREPARING_PROOF',note:'Bring the evidence forward.',marks:['Found: a person with real pain','Observed: actual evidence','Inferred: an interpretation']},
 {title:'The next move is human.',description:'You get promising prospects, useful proof and the original conversations. You decide whether to engage, and how to make it helpful.',stage:'QUALIFIED',note:'A better introduction begins with useful work.',marks:['Useful proof','Honest limitations','Your decision']}
];
export function ProductStory(){
 const [active,setActive]=useState(0),nodes=useRef<(HTMLElement|null)[]>([]);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>{const visible=entries.filter(x=>x.isIntersecting).sort((a,b)=>Math.abs(a.boundingClientRect.top-innerHeight*.28)-Math.abs(b.boundingClientRect.top-innerHeight*.28));if(visible[0])setActive(Number((visible[0].target as HTMLElement).dataset.chapter));},{rootMargin:'-10% 0px -45% 0px',threshold:0});nodes.current.forEach(el=>el&&observer.observe(el));return()=>observer.disconnect();},[]);
 return <section className="product-story" id="how-hallar-works"><div className="story-introduction"><Reveal><span className="eyebrow">HOW HALLAR WORKS</span><h2>A little less noise.<br/><em>A much better reason.</em></h2><p>Follow your product brief to a real person you can genuinely help, with useful proof before you reach out.</p></Reveal><a className="story-start" href="#product-url">Start with your product <Arrow/></a></div><div className="story-sequence"><aside className="story-guide" data-story-active={active+1}><div className="guide-top"><span>FIELD NOTES</span><span>{String(active+1).padStart(2,'0')} / 05</span></div><div className="guide-scenery"><span className="guide-crosshair"/><ScoutAvatar stage={chapters[active].stage}/><div className="signal-path"/><span className="guide-caption">{chapters[active].note}</span></div><div className="guide-markers">{chapters.map((x,i)=><a key={x.title} href={'#story-'+(i+1)} aria-label={'Story chapter '+(i+1)} aria-current={active===i?'step':undefined} className={active===i?'is-active':''}><span>{String(i+1).padStart(2,'0')}</span><i/></a>)}</div></aside><div className="story-chapters">{chapters.map((chapter,i)=><article className={'story-chapter story-chapter-'+(i+1)} id={'story-'+(i+1)} data-chapter={i} key={chapter.title} ref={el=>{nodes.current[i]=el;}}><Reveal className="story-copy"><span className="story-number">0{i+1}<i/></span><h3>{chapter.title}</h3><p>{chapter.description}</p><div className="story-artifact">{chapter.marks.map((mark,index)=><div key={mark}><Glyph kind={i===2?(index===0?'cross':index===1?'question':'search'):i===4?'check':i===3?'note':'link'}/><span>{mark}</span></div>)}</div><div className="mobile-story-guide"><ScoutAvatar stage={chapter.stage}/><span>{chapter.note}</span></div></Reveal></article>)}</div></div><Reveal className="story-close"><span className="eyebrow">ONLY WHAT HOLDS UP</span><h2>Not more people.<br/><em>The right reason to help.</em></h2><a href="#product-url" className="button primary">Tell Hallar about your product <Arrow/></a></Reveal></section>;
}
